title: Frugaliz
description: Trié par l'IA. Validé pour toi.
baseurl: "/frugaliz-blog"
url: "https://Frugaliz.github.io"

remote_theme: pages-themes/midnight

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-remote-theme
